#!/bin/sh
# ==================================================================
# FILE     key-handler
# MACHINE  all
# INFO     external keys for sxiv
#
# DATE     09.05.2020
# OWNER    Bischofberger
# ==================================================================

while read file
do
  case "$1" in
    "X")
      #trash "$file"
      mv -f "$file" ~/.trash
      mv -f "${file%.*}.RAF" ~/.trash
      mv -f "${file%.*}.NEF" ~/.trash
      mv -f "${file%.*}.DNG" ~/.trash
      ;;
    "R")
      convert -rotate 90 "$file" "$file"
      ;;
    "r")
      convert -rotate -90 "$file" "$file"
      ;;
    "C-c")
      echo -n "$file" | xsel -b -i
      echo -n "$file" | xsel -p -i
      ;;
  esac
done
