#!/bin/sh
# ==================================================================
# FILE     key-handler
# MACHINE  all
# INFO     external keys for sxiv
#
# DATE     10.09.2017
# OWNER    Bischofberger
# ==================================================================

while read file
do
  case "$1" in
    "X")
      #trash "$file"
      mv "$file" ~/.trash
      ;;
    "R")
      convert -rotate 90 "$file" "$file"
      ;;
    "C-c")
      echo -n "$file" | xsel -b -i
      echo -n "$file" | xsel -p -i
      ;;
  esac
done
